spring:
  application:
    name: findr-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/findr}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

server:
  error:
    include-message: never
  port: ${SERVER_PORT:8888}

application:
  web:
    allowed-origins: ${APP_ALLOWED_ORIGINS:http://localhost:19006,http://localhost:8081,http://localhost:3000}
  security:
    firebase:
      project-id: ${FIREBASE_PROJECT_ID:}
    jwt:
      secret-key: ${JWT_SECRET_KEY:316c0a2a82b1cda7e48bfd32737b7d38043c574be0cbf92180f7a57fb35e5b40}
      expiration: ${JWT_EXPIRATION_MS:900000}
    refresh-token:
      secret-key: ${REFRESH_TOKEN_SECRET_KEY:3FDC8124AE03656BFEFABC3C925B18372147D12FA177885827D00A16A73A9014}
      expiration: ${REFRESH_TOKEN_EXPIRATION_MS:864000000}
