spring:
  application:
    name: findr-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/findr}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

server:
  error:
    include-message: never
  port: ${SERVER_PORT:8888}

application:
  web:
    allowed-origins: ${APP_ALLOWED_ORIGINS:http://localhost:19006,http://localhost:8081,http://localhost:3000}
  security:
    firebase:
      project-id: ${FIREBASE_PROJECT_ID:}
