CREATE SEQUENCE IF NOT EXISTS category_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS checkout_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS coordinate_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS store_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS traffic_flow_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS category (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(255),
  category_id BIGINT NOT NULL REFERENCES category(id),
  is_golden BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_is_golden ON product(is_golden);

CREATE TABLE IF NOT EXISTS store (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS checkout (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS traffic_flow (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS item_coordinate (
  id BIGINT PRIMARY KEY,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  store_id BIGINT REFERENCES store(id),
  product_id BIGINT REFERENCES product(id),
  checkout_id BIGINT REFERENCES checkout(id),
  traffic_flow_id BIGINT REFERENCES traffic_flow(id)
);
